Fix threshold for applying 0 padding when encoding hex
denodrivers/postgres pull request #304
Opened 2021-06-22 02:21 UTC by voltrevo

```diff
-val < 10 ? `0${val.toString(16)}` : val.toString(16))
+val < 0x10 ? `0${val.toString(16)}` : val.toString(16))
```

E.g. when `val` is 11 it should encode as `"0b"` but 11 is not less than 10 so it doesn't get padded.

2021-06-22 18:11 UTC, Soremwar commented
Hi there @voltrevo, thank you for your contribution

2021-06-22 18:12 UTC, Soremwar requested changes
Can you please add a regression test in `data_types_test.ts` showing the error you encountered previously? That should be all, clean fix

2021-06-22 23:11 UTC, voltrevo commented
@Soremwar The `"\\x02af4"` test had to be updated because it was padding incorrectly. Nevertheless, I've added another one that shows the issue more clearly (`[11] -> "\\x0b"`).

2021-06-23 18:35 UTC, Soremwar approved these changes
Thanks, this is the kind of stuff that really slips under your radar

2021-06-23 18:36 UTC, merged