feat: add support for sslmode=disable
denodrivers/postgres pull request #309
Opened 2021-07-27 15:50 UTC by lucacasonato

Adds support for sslmode "disable".

2021-08-02 02:37 UTC, Soremwar requested changes

2021-08-02 02:37 UTC, Soremwar commented on tests/connection_params_test.ts
> +    "Supplied DSN has invalid sslmode 'verify-full'. Only 'require' or 'prefer' are supported",
Only 'require', 'prefer' and 'disable' are supported

2021-08-02 02:37 UTC, Soremwar commented on connection/connection.ts
> +    if (isTLSEnabled) {
Per spec, all PostgreSQL servers with TLS encryption support (all supported versions) must start a connection asking whether of not the server is willing to create a TLS connection, even if the user requested TLS to be disabled. Simply move the "is TLS enabled" condition after the serverAcceptsTLS check to resolve this

2021-09-25 11:53 UTC, twhitbeck commented
we need this to be able to use this drive to connect to postgres instances on [fly](https://fly.io/docs/reference/postgres/)

2021-09-25 17:19 UTC, Soremwar approved these changes
LGTM, thank you Luca

2021-09-25 17:20 UTC, merged