feat: Option to automatically turn snake_case columns in a query response into camelCase fields #310
denodrivers/postgres pull request #311
Opened 2021-08-10 05:47 UTC by pantapita

I've been using this feature and it works well (see the proposed changes). I didn't implement the switch as it should be compliant with the vision of the authors, so please advise where to put the switch and how to name it ?
I'm addressing "query.ts -> snakeToCamel" in particular !

Best

2021-09-26 19:07 UTC, Soremwar commented
Hi @pantapita, the option to rename the fields to camelcase should be added here
https://github.com/denodrivers/postgres/blob/235d57568bd3a49c353a988918d06077197e9044/query/query.ts#L53
in a per query basis

Thanks for your contribution!

2021-09-27 19:58 UTC, Soremwar requested changes

2021-09-27 19:58 UTC, Soremwar commented on query/query.ts
> +  snakeToCamel?: boolean;
Name the argument as camelcase, i'll take care of adding it to the docs later

2021-09-27 19:58 UTC, Soremwar commented on query/query.ts
> +  snakeToCamel?: boolean;
Add the option to the QueryObjectConfig interface, since QueryConfig applies to queryArray which contains no query names

2021-09-27 20:01 UTC, Soremwar commented
While reviewing I realized that this implementation only renames the fields passed to the `fields` argument, instead of renaming the fields returned naturally by the database, which is the feature requested by the issue #310

I don't think it's worth adding to the codebase unless that particular issue is addressed, since the `fields` parameter can be all camelcase by simple action of the user

2021-09-28 22:20 UTC, lucacasonato commented
If it helps, this is the conversion function I used for a local project of mine:

```ts
/** Given an object that uses snake_case keys, turn it into an object using camelCase keys */
export function camelCaseify<T>(obj: Record<string, unknown>): T {
  const result: Record<string, unknown> = {};
  for (const snakeCasedKey in obj) {
    const camelCasedKey = snakeCasedKey
      .replaceAll(/_([a-z])/g, (g) => g[1].toUpperCase());
    result[camelCasedKey] = obj[snakeCasedKey];
  }
  return result as T;
}
```

2021-09-30 22:40 UTC, Soremwar commented
Superseded by #333

2021-09-30 22:40 UTC, closed without merging