`mod.ts`: check for appropriate v8 version
denodrivers/postgres pull request #455
Opened 2024-02-08 13:39 UTC by montyanderson

We run `deno-postgres` for some of our API services. During a recent upgrade we had query failures due to no support for `Promise.withResolvers()`. This change adds a check for at least V8 version 12 where that API was added.

2024-02-08 17:24 UTC, groksrc commented
Fwiw, I also ran across this error today and can confirm its existence.

2024-02-09 01:11 UTC, iuioiua commented on mod.ts
> +if(Number(Deno.version.v8.split(".")[0]) < 12) {
```suggestion
if(Deno.version.deno >= 1.38) {
```
This might work fine.

2024-02-12 04:30 UTC, bombillazo requested changes
Simplify condition

2024-02-12 04:30 UTC, bombillazo commented on mod.ts
> +if(Number(Deno.version.v8.split(".")[0]) < 12) {
shouldnt it be `<=` ?

2024-02-27 23:36 UTC, langpavel requested changes
- ❌ Comment is misleading. Deno.version.v8 in comment vs Deno.version.deno in code
- ❌ Really you want compare string with float converted to string?

2024-03-02 05:57 UTC, iuioiua requested changes
Please run `deno fmt` and see the above suggestions.

2024-03-04 15:37 UTC, closed without merging